### ISSUE TITLE
Reason of incompatibility with BattlEye

### ISSUE THREAD

**Issue by TibiaBaker** [jo3bingham/TibiaAPI#44]
Hello,

I'm new to all the new Open Tibia stuff, because I'm returning after years of absence. Please forgive me if this is a silly question to ask, but since it's hard to find good information on the topic, I'll try.

> Because of BattlEye, Windows support is limited to official servers not protected by BattlEye (Zuna and Zunera).

What is the reason of incompatibility with BattlEye? Is this just because BattlEye would detect modifications of the client, or maybe it additionally encrypts traffic sent by Tibia client?

**Comment by jo3bingham** [comment]
On Windows, BattlEye performs checks on the client executable as it is being started to ensure no modifications have been made to the process memory. Since the `loginWebService` address and the RSA key have to be modified in order to work with the API, BattlEye would then block the client from loading. However, if you were able to bypass this restriction then you could use the API with any world on Windows. But I see that as wasted effort because you can spin up a Linux VM for free where BattlEye is less invasive, and you're able to use the API with any world.

**Comment by TibiaBaker** [comment]
So BattlEye doesn't perform VM checks on Linux?

**Comment by jo3bingham** [comment]
> So BattlEye doesn't perform VM checks on Linux?

Nope.

**Comment by GittCatt** [comment]
That is a botter's paradise, then. While your project is obviously not about that, it could be used to make a new BlackD Proxy, I suppose.

**Comment by TibiaBaker** [comment]
That is a botter's paradise, then. While your project is obviously not about that, it could be used to make a new BlackD Proxy, I suppose.

**Comment by jo3bingham** [comment]
> That is a botter's paradise, then. While your project is obviously not about that, it could be used to make a new BlackD Proxy, I suppose.

Yeah, it could definitely be used to make a proxy bot akin to BlackD Proxy. I actually made a proof-of-concept bot with it, but it was very limited (heal/mana (self/friends), attack, refill, equip, and some other minor functionality) because I have no desire to make a full-fledged bot.

Closing this issue now since your question has been answered.
