### ISSUE TITLE
Question: Client version

### ISSUE THREAD

**Issue by omarcopires** [jo3bingham/TibiaAPI#48]
If I'm trying to use a client version that doesn't have the package.json file, is there any way I can register it so I can record a session?

**Comment by Ezipsoft** [comment]
Gunzodus doesn't have a package.json file with the client version, which will cause some issues, but you can easily fix it. All you have to do is create a package.json file with this json:
JSON:
{
  "version": "12.00.7695"
}
and place it in the main directory (where the assets and bin folders are). You'll want to do the same thing for any other OTs that don't have a package.json file. And you have to use the actual client version; which you can find by launching the client and going into the settings (Gunzodus claims to offer the 12.40 client, but it's actually 12.00.7695). This is important because the API depends on the correct client version to parse packets correctly.

Joe teachs me about that.
